### ISSUE TITLE
Add examples for React Conflux

### ISSUE THREAD

**Issue by nwthomas** [dustinmyers/react-conflux#3]
Build out example app library in documentation including:
- [x] Counter app
- [x] To-do app
- [ ] Pseudo sign-in
- [ ] Multiple component tree state
- [ ] Asynchronous

**Comment by jsifalda** [comment]
no real word example? I would love to see how this gonna looks like for big application... will that help with splitting big codebase into small independent packages?

**Comment by dustinmyers** [comment]
@jsifalda Thanks for checking this library out. We are still in beta and will have a docs page up soon with more examples there.
